export const blockchain = {
  1: "ethereum",
  56: "bsc",
  137: "polygon",
  1313161554: "aurora",
  43114: "avalanche",
  250: "fantom",
  66: "okchain",
  321: "kcc",
  322: "kcc",
  288: "boba",
  11: "aptos",
  2: "aptostest",
  65: "okchain",
  97: "bsc_test",
  42161: "arbitrum",
  701: "ton",
  702: "ton",
  711: "ton",
  4689: "iotex",
  4690: "iotextest",
  324: "zksync",
  77: "sui_test",
  88: "sui",
  1030: "espace",
  31337: "polygon",
  12008: "opside",
  534351: "scroll_test",
  534352: "scroll",
  59144: "linea",
  801: "solana",
  8453: "base",
  1101: "polygon_zkevm",
  888: "sei",
  10: "optimism",
  110: "cardano",
  169: "manta",
  196: "xlayer",
  1111: "bitcoin",
  1116: "core_dao",
};

export const wrapBlockchain = {
  ethereum: "Ethereum",
  ethereum_fork: "Ethereum fork",
  bsc: "BNB Chain",
  bsc_test: "BNB Chain Test",
  polygon: "Polygon",
  aurora: "Aurora",
  avalanche: "Avalanche",
  fantom: "Fantom",
  okchain: "OKXChain",
  kcc: "KCC",
  boba: "Boba",
  aptos: "Aptos Mainnet",
  aptostest: "Aptos Testnet",
  okc: "OKC-test",
  arbitrum: "Arbitrum One",
  ton: "TON ",
  openmasktest: "Open Mask Test",
  iotex: "IoTeX",
  iotextest: "IoTeX Testnet",
  zksync: "zkSync",
  sui_test: "Sui Test",
  sui: "Sui",
  espace: "Conflux eSpace",
  opside: "Opside",
  scroll_test: "Scroll Sepolia",
  scroll: "Scroll",
  linea: "Linea",
  solana: "Solana",
  base: "Base",
  polygon_zkevm: "Polygon zkEVM",
  sei: "Sei",
  optimism: "Optimism",
  cardano: "Cardano",
  manta: "Manta Network",
  xlayer: "X Layer",
  bitcoin: "Bitcoin",
  core_dao: "Core",
};

export const networkIcon = {
  1: "/imgs/web3/chains/ethereum.svg",
  31337: "/imgs/web3/chains/polygon.svg",
  56: "/imgs/web3/chains/bnbchain.svg",
  97: "/imgs/web3/chains/bnbchain.svg",
  137: "/imgs/web3/chains/polygon.svg",
  1313161554: "/imgs/web3/chains/aurora.svg",
  43114: "/imgs/web3/chains/avalanche.svg",
  250: "/imgs/web3/chains/fantom.svg",
  66: "/imgs/web3/chains/okxchain.svg",
  321: "/imgs/web3/chains/kcc.svg",
  322: "/imgs/web3/chains/kcc.svg",
  288: "/imgs/web3/chains/boba.svg",
  11: "/imgs/web3/chains/aptos.svg",
  2: "/imgs/web3/chains/aptos.svg",
  42161: "/imgs/web3/chains/arbitrum.svg",
  701: "/imgs/web3/chains/openmask.svg",
  702: "/imgs/web3/chains/openmask.svg",
  711: "/imgs/web3/chains/tonkeeper.svg",
  4689: "/imgs/web3/chains/iotex.svg",
  4690: "/imgs/web3/chains/iotex.svg",
  324: "/imgs/web3/chains/zksync.svg",
  77: "/imgs/web3/wallets/sui_wallet.svg",
  88: "/imgs/web3/wallets/sui_wallet.svg",
  1030: "/imgs/web3/chains/espace.svg",
  12008: "/imgs/web3/chains/opside.svg",
  534351: "/imgs/web3/chains/scroll.svg",
  534352: "/imgs/web3/chains/scroll.svg",
  59144: "/imgs/web3/chains/linea.svg",
  8453: "/imgs/web3/chains/base.svg",
  801: "/imgs/web3/chains/solana.svg",
  1101: "/imgs/web3/chains/polygon.svg",
  888: "/imgs/web3/chains/sei.svg",
  10: "/imgs/web3/chains/op.svg",
  110: "/imgs/web3/chains/cardano.svg",
  169: "/imgs/web3/chains/manta.svg",
  196: "/imgs/web3/chains/okxchain.svg",
  1111: "/imgs/web3/chains/btc.svg",
  1116: "/imgs/web3/chains/core.svg",
};

export const bqlNetwork = [
  {
    name: "Ethereum",
    value: "ethereum",
    logo: "/imgs/web3/chains/ethereum.svg",
  },
  {
    name: "BNB Chain",
    value: "bsc",
    logo: "/imgs/web3/chains/bnbchain.svg",
  },
  {
    name: "BNB Chain Test",
    value: "bsc_test",
    logo: "/imgs/web3/chains/bnbchain.svg",
  },
  {
    name: "Polygon",
    value: "polygon",
    logo: "/imgs/web3/chains/polygon.svg",
  },
  {
    name: "Solana",
    value: "solana",
    logo: "/imgs/web3/chains/solana.svg",
  },
  {
    name: "X Layer",
    value: "xlayer",
    logo: "/imgs/web3/chains/okxchain.svg",
  },
  {
    name: "Aurora",
    value: "aurora",
    logo: "/imgs/web3/chains/aurora.svg",
  },
  {
    name: "Avalanche",
    value: "avalanche",
    logo: "/imgs/web3/chains/avalanche.svg",
  },
  {
    name: "Fantom",
    value: "fantom",
    logo: "/imgs/web3/chains/fantom.svg",
  },
  {
    name: "OKXChain",
    value: "okchain",
    logo: "/imgs/web3/chains/okxchain.svg",
  },
  {
    name: "KCC",
    value: "kcc",
    logo: "/imgs/web3/chains/kcc.svg",
  },
  {
    name: "Boba",
    value: "boba",
    logo: "/imgs/web3/chains/boba.svg",
  },
  {
    name: "Arbitrum One",
    value: "arbitrum",
    logo: "/imgs/web3/chains/arbitrum.svg",
  },
  {
    name: "IoTeX",
    value: "iotex",
    logo: "/imgs/web3/chains/iotex.svg",
  },
  {
    name: "zkSync",
    value: "zksync",
    logo: "/imgs/web3/chains/zksync.svg",
  },
  {
    name: "Conflux eSpace",
    value: "espace",
    logo: "/imgs/web3/chains/espace.svg",
  },
  {
    name: "Opside",
    value: "opside",
    logo: "/imgs/web3/chains/opside.svg",
  },
  {
    name: "Scroll Sepolia",
    value: "scroll_test",
    logo: "/imgs/web3/chains/scroll.svg",
  },
  {
    name: "Scroll",
    value: "scroll",
    logo: "/imgs/web3/chains/scroll.svg",
  },
  {
    name: "Optimism",
    value: "optimism",
    logo: "/imgs/web3/chains/op.svg",
  },
  {
    name: "Manta Network",
    value: "manta",
    logo: "/imgs/web3/chains/manta.svg",
  },
  {
    name: "Base",
    value: "base",
    logo: "/imgs/web3/chains/base.svg",
  },
  {
    name: "Core",
    value: "core_dao",
    logo: "/imgs/web3/chains/core.svg",
  },
];

export const networkParam = {
  1: {
    chainId: "0x1",
    chainName: "Ethereum",
    nativeCurrency: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://mainnet.infura.io/v3"],
    blockExplorerUrls: ["https://etherscan.com"],
  },
  31337: {
    chainId: "0x7a69",
    chainName: "Ethereum fork",
    nativeCurrency: {
      name: "Ethereum fork",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["http://192.168.31.161:8545"],
    blockExplorerUrls: ["https://etherscan.com"],
  },
  56: {
    chainId: "0x38",
    chainName: "Binance Smart Chain",
    nativeCurrency: {
      name: "Binance Coin",
      symbol: "BNB",
      decimals: 18,
    },
    rpcUrls: ["https://bsc-dataseed.binance.org"],
    blockExplorerUrls: ["https://bscscan.com"],
  },
  97: {
    chainId: "0x61",
    chainName: "Binance Smart Chain Testnet",
    nativeCurrency: {
      name: "Binance Coin",
      symbol: "BNB",
      decimals: 18,
    },
    rpcUrls: ["https://data-seed-prebsc-1-s1.binance.org:8545"],
    blockExplorerUrls: ["https://testnet.bscscan.com"],
  },
  137: {
    chainId: "0x89",
    chainName: "Polygon",
    nativeCurrency: {
      name: "Matic",
      symbol: "MATIC",
      decimals: 18,
    },
    rpcUrls: ["https://rpc-mainnet.maticvigil.com"],
    blockExplorerUrls: ["https://polygonscan.com/"],
  },
  1313161554: {
    chainId: "0x4e454152",
    chainName: "Aurora MainNet",
    nativeCurrency: {
      name: "Ether",
      symbol: "aETH",
      decimals: 18,
    },
    rpcUrls: ["https://mainnet.aurora.dev"],
    blockExplorerUrls: ["https://explorer.mainnet.aurora.dev"],
  },
  43114: {
    chainId: "0xA86A",
    chainName: "Avalanche",
    nativeCurrency: {
      name: "Avalanche Token",
      symbol: "AVAX",
      decimals: 18,
    },
    rpcUrls: ["https://api.avax.network/ext/bc/C/rpc"],
    blockExplorerUrls: ["https://explorer.avax.network"],
  },
  250: {
    chainId: "0xfa",
    chainName: "Fantom",
    nativeCurrency: {
      name: "Fantom",
      symbol: "FTM",
      decimals: 18,
    },
    rpcUrls: ["https://rpcapi.fantom.network"],
    blockExplorerUrls: ["https://ftmscan.com"],
  },
  66: {
    chainId: "0x42",
    chainName: "OKXChain Mainnet",
    nativeCurrency: {
      name: "OKXChain Global Utility Token",
      symbol: "OKT",
      decimals: 18,
    },
    rpcUrls: ["https://exchainrpc.okex.org"],
    blockExplorerUrls: ["https://www.oklink.com/en/okc"],
  },
  321: {
    chainId: "0x141",
    chainName: "KCC Mainnet",
    nativeCurrency: {
      name: "KuCoin Token",
      symbol: "KCS",
      decimals: 18,
    },
    rpcUrls: ["https://rpc-mainnet.kcc.network"],
    blockExplorerUrls: ["https://explorer.kcc.io"],
  },
  288: {
    chainId: "0x120",
    chainName: "Boba Network",
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://mainnet.boba.network/"],
    blockExplorerUrls: ["https://bobascan.com"],
  },
  42161: {
    chainId: "0xa4b1",
    chainName: "Arbitrum One",
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://rpc.ankr.com/arbitrum "],
    blockExplorerUrls: ["https://arbiscan.io"],
  },
  4689: {
    chainId: "0x1251",
    chainName: "IoTeX Mainnet",
    nativeCurrency: {
      name: "IOTX",
      symbol: "IOTX",
      decimals: 18,
    },
    rpcUrls: ["https://babel-api.mainnet.iotex.io"],
    blockExplorerUrls: ["https://iotexscan.io"],
  },
  4690: {
    chainId: "0x1252",
    chainName: "IoTeX Testnet",
    nativeCurrency: {
      name: "IOTX",
      symbol: "IOTX-T",
      decimals: 18,
    },
    rpcUrls: ["https://babel-api.testnet.iotex.io"],
    blockExplorerUrls: ["https://testnet.iotexscan.io"],
  },
  324: {
    chainId: "0x144",
    chainName: "zkSync Era Mainnet",
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://mainnet.era.zksync.io"],
    blockExplorerUrls: ["https://explorer.zksync.io"],
  },
  1030: {
    chainId: "0x406",
    chainName: "Conflux eSpace",
    nativeCurrency: {
      name: "CFX",
      symbol: "CFX",
      decimals: 18,
    },
    rpcUrls: ["https://evm.confluxrpc.com"],
    blockExplorerUrls: ["https://evm.confluxscan.net"],
  },
  12008: {
    chainId: "0x2ee8",
    chainName: "Opside Public zkEVM V2",
    nativeCurrency: {
      name: "IDE",
      symbol: "IDE",
      decimals: 18,
    },
    rpcUrls: ["https://pre-alpha-zkrollup-rpc.opside.network/public"],
    blockExplorerUrls: ["https://public.zkevm.opside.info"],
  },
  534351: {
    chainId: "0x8274f",
    chainName: "Scroll Sepolia Test",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://sepolia-rpc.scroll.io"],
    blockExplorerUrls: ["https://sepolia.scrollscan.dev"],
  },
  534352: {
    chainId: "0x82750",
    chainName: "Scroll",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://rpc.scroll.io"],
    blockExplorerUrls: ["https://blockscout.scroll.io"],
  },
  59144: {
    chainId: "0xe708",
    chainName: "Linea",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://linea-mainnet.infura.io/v3"],
    blockExplorerUrls: ["https://lineascan.build/"],
  },
  8453: {
    chainId: "0x2105",
    chainName: "Base",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://developer-access-mainnet.base.org"],
    blockExplorerUrls: ["https://base.blockscout.com/"],
  },
  10: {
    chainId: "0xa",
    chainName: "OP Mainnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://mainnet.optimism.io"],
    blockExplorerUrls: ["https://optimistic.etherscan.io"],
  },
  1101: {
    chainId: "0x44d",
    chainName: "Polygon zkEVM",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://rpc.ankr.com/polygon_zkevm"],
    blockExplorerUrls: ["https://zkevm.polygonscan.com"],
  },
  169: {
    chainId: "0xa9",
    chainName: "Manta Pacific Mainnet",
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: ["https://pacific-rpc.manta.network/http"],
    blockExplorerUrls: ["https://pacific-explorer.manta.network"],
  },
  196: {
    chainId: "0xc4",
    chainName: "X Layer",
    nativeCurrency: {
      name: "OKB",
      symbol: "OKB",
      decimals: 18,
    },
    rpcUrls: ["https://rpc.xlayer.tech", "https://xlayerrpc.okx.com"],
    blockExplorerUrls: ["https://www.okx.com/explorer/xlayer"],
  },
  1116: {
    chainId: "0x45c",
    chainName: "Core Blockchain Mainnet",
    nativeCurrency: {
      name: "CORE",
      symbol: "CORE",
      decimals: 18,
    },
    rpcUrls: ["https://rpc.coredao.org"],
    blockExplorerUrls: ["https://scan.coredao.org"],
  },
};
